/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.gui;

import edu.esprit.dao.RestaurantDAO;
import edu.esprit.entities.restaurant;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class jGererResto extends javax.swing.JFrame {

    /**
     * Creates new form jGererResto
     */
    public jGererResto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        bt_ajouter = new javax.swing.JButton();
        bt_modifier = new javax.swing.JButton();
        bt_supprimer = new javax.swing.JButton();
        bt_annuler = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableResto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_nom = new javax.swing.JTextField();
        tf_adresse = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_tel = new javax.swing.JTextField();
        tf_site = new javax.swing.JTextField();
        tf_heurO = new javax.swing.JTextField();
        tf_heurC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_description = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 101, 101));

        bt_ajouter.setText("Ajouter");
        bt_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ajouterActionPerformed(evt);
            }
        });

        bt_modifier.setText("Modifier");
        bt_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modifierActionPerformed(evt);
            }
        });

        bt_supprimer.setText("Supprimer");
        bt_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimerActionPerformed(evt);
            }
        });

        bt_annuler.setText("Annuler");
        bt_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_annulerActionPerformed(evt);
            }
        });

        JTableResto.setModel(new GererRestaurant());
        JTableResto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableRestoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableResto);

        jLabel1.setText(" Identifiant :");

        jLabel2.setText("Nom :");

        jLabel3.setText("Adresse :");

        jLabel4.setText("E-mail :");

        jLabel6.setText("Téléphone :");

        jLabel7.setText("Site web :");

        jLabel8.setText("Heures d'ouverture :");

        jLabel9.setText("Heures de fermeture :");

        jLabel10.setText("Description :");

        tf_id.setEnabled(false);

        ta_description.setColumns(20);
        ta_description.setRows(5);
        jScrollPane2.setViewportView(ta_description);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_nom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(tf_adresse, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_email, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_tel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_site, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_heurO, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_heurC, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(bt_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_supprimer)
                        .addGap(18, 18, 18)
                        .addComponent(bt_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_site, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_heurO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_heurC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_ajouter)
                            .addComponent(bt_modifier)
                            .addComponent(bt_supprimer)
                            .addComponent(bt_annuler))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 62, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Gérer restaurant", jPanel2);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/images/resto_header_logo.png"))); // NOI18N

        jLabel11.setText("Bienvenu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(334, 334, 334)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_annulerActionPerformed
        
        tf_nom.setText("");
         tf_adresse.setText("");
          tf_email.setText("");
           ta_description.setText("");
            tf_tel.setText("");
             tf_site.setText("");
              tf_heurO.setText("");
               tf_heurC.setText("");
    }//GEN-LAST:event_bt_annulerActionPerformed

    private void bt_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimerActionPerformed

        GererRestaurant GR = new GererRestaurant();
        int x = JTableResto.getSelectedRow();
        if(x==-1){
            
            JOptionPane.showMessageDialog( this, "Veuillez sélectionner un restaurant !");

        }
        else
        {
            int id = Integer.parseInt( GR.getValueAt(x , 0).toString());
            System.out.println(id);
            new RestaurantDAO().deleteRestaurant(id);
            GR.listRestaurant = new RestaurantDAO().DisplayAllRestaurant();
            JTableResto.setModel(GR);
            JOptionPane.showMessageDialog( this, "Suppression effectuée avec succés !");

        }

    }//GEN-LAST:event_bt_supprimerActionPerformed

    private void bt_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ajouterActionPerformed
      
                                            
        if ((tf_nom.getText().isEmpty())||(tf_adresse.getText().isEmpty())||(tf_email.getText().isEmpty())||
            (ta_description.getText().isEmpty())||(tf_tel.getText().isEmpty())||(tf_heurO.getText().isEmpty())||
            (tf_heurC.getText().isEmpty())) {
            
            
            JOptionPane.showMessageDialog( this, "Veuillez saisir toutes les champs !");
        }
        else
        {
        restaurant resto = new restaurant();
        RestaurantDAO restaurantDAO = new RestaurantDAO();
        resto.setNom(tf_nom.getText());
        resto.setAdresse(tf_adresse.getText());
        resto.setEmail(tf_email.getText());
        resto.setDescription(ta_description.getText());
        resto.setTel(tf_tel.getText());
        resto.setSite(tf_site.getText());
        resto.setHeure_ouverture(tf_heurO.getText());
        resto.setHeure_fermeture(tf_heurC.getText());
        restaurantDAO.insertRestaurant(resto);
        JOptionPane.showMessageDialog( this, "Ajout effectué avec succés !");
    }
       JTableResto.setModel(new GererRestaurant());
        
    }//GEN-LAST:event_bt_ajouterActionPerformed

    private void bt_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modifierActionPerformed
        
            if ((tf_nom.getText().isEmpty())||(tf_adresse.getText().isEmpty())||(tf_email.getText().isEmpty())||
            (ta_description.getText().isEmpty())||(tf_tel.getText().isEmpty())||(tf_heurO.getText().isEmpty())||
            (tf_heurC.getText().isEmpty())) {
            
            
            JOptionPane.showMessageDialog( this, "Veuillez saisir toutes les champs !");
        }
        else
        {
        
        restaurant rest = new restaurant();
        rest.setId(Integer.parseInt(tf_id.getText()));
        rest.setAdresse(tf_adresse.getText());
        rest.setDescription(ta_description.getText());
        rest.setEmail(tf_email.getText());
        rest.setHeure_fermeture(tf_heurC.getText());
        rest.setHeure_ouverture(tf_heurC.getText());
        rest.setNom(tf_nom.getText());
        rest.setSite(tf_site.getText());
        rest.setTel(tf_tel.getText());
        new  RestaurantDAO().updateRestaurant(rest);
        JTableResto.setModel(new GererRestaurant());
        JOptionPane.showMessageDialog( this, "Modification appliquée avec succès !");
        }

    }//GEN-LAST:event_bt_modifierActionPerformed

    private void JTableRestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableRestoMouseClicked
        tf_id.setText(JTableResto.getValueAt(JTableResto.getSelectedRow(), 0).toString());
        tf_nom.setText(JTableResto.getValueAt(JTableResto.getSelectedRow(), 1).toString());
        tf_adresse.setText(JTableResto.getValueAt(JTableResto.getSelectedRow(), 3).toString());
        tf_email.setText(JTableResto.getValueAt(JTableResto.getSelectedRow(), 2).toString());
        tf_heurC.setText(JTableResto.getValueAt(JTableResto.getSelectedRow(), 8).toString());
        tf_heurO.setText(JTableResto.getValueAt(JTableResto.getSelectedRow(), 7).toString());
        tf_site.setText(JTableResto.getValueAt(JTableResto.getSelectedRow(), 6).toString());
        tf_tel.setText(JTableResto.getValueAt(JTableResto.getSelectedRow(), 5).toString());
        ta_description.setText(JTableResto.getValueAt(JTableResto.getSelectedRow(), 4).toString());      
    }//GEN-LAST:event_JTableRestoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jGererResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jGererResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jGererResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jGererResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jGererResto().setVisible(true);
               
            }
            
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableResto;
    private javax.swing.JButton bt_ajouter;
    private javax.swing.JButton bt_annuler;
    private javax.swing.JButton bt_modifier;
    private javax.swing.JButton bt_supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea ta_description;
    private javax.swing.JTextField tf_adresse;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_heurC;
    private javax.swing.JTextField tf_heurO;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nom;
    private javax.swing.JTextField tf_site;
    private javax.swing.JTextField tf_tel;
    // End of variables declaration//GEN-END:variables
}
